### ISSUE TITLE
replace homepage mapbox with jpg of the same

### ISSUE THREAD

**Issue by vcavallo** [nycmeshnet/nycmeshnet.github.io#1]

**Comment by bhny** [comment]
this is important for two reasons- 
• it is really slow to load, so often a user will see just a white page with a bit of text
• mapbox charges per tile loaded and I pay the bill!

**Comment by bhny** [comment]
fixed in latest at http://nycmeshnet.github.io/, 
asked Peter to push it, so it will be live soon
