### ISSUE TITLE
Title and nav text outline not visible on map in Chrome

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmeshnet.github.io#15]
OSX 10.9.5, Chrome  47.0.2526.111
Text initially appears with shadow outline but then outline disappears. This is only on the map page and only in Chrome.
Chrome (problem)
<img width="629" alt="mapchrome" src="https://cloud.githubusercontent.com/assets/1037006/12515898/a88ab6d4-c0f8-11e5-84ef-6a2d688fab02.png">
Safari (correct)
<img width="628" alt="mapsafari" src="https://cloud.githubusercontent.com/assets/1037006/12515908/ae74cefe-c0f8-11e5-8ea9-3d8d16dff94a.png">

**Comment by xtream1101** [comment]
I was not able to reproduce this bug, tried clicking around and zooming but I still have the outline. 
If anyone else has this problem please comment to let me know.

Tested with:
OSX 10.11.3
Chrome 47.0.2526.111

**Comment by bhny** [comment]
It happens on OSX 10.9.5, and 10.6.8 (both my laptops)
I found the line that needs to be removed-

<img width="726" alt="text-shadow" src="https://cloud.githubusercontent.com/assets/1037006/12532116/99a9c272-c1d9-11e5-880a-135eddd069ed.png">

**Comment by bhny** [comment]
It was a chrome extension A+ Font Rendering Enhancer 0.1.4.1. Turned it of and shadow came back.
