### ISSUE TITLE
one-time donation field buggy

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmeshnet.github.io#17]
The dollar sign should probably disappear on click. At the moment you can put the insertion point before the dollar and it will type more dollar signs.
<img width="189" alt="one-time-donation" src="https://cloud.githubusercontent.com/assets/1037006/17021260/f1c5cc26-4f14-11e6-8293-6b486d685128.png">

**Comment by nycoliver** [comment]
Fixed
