### ISSUE TITLE
remove confusing "8/207" on right side of Slack button

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmeshnet.github.io#25]
Slack button has online and registered user count which isn't necessary and is confusing

**Comment by jedahan** [comment]
Ok, so I [forked slackin](github.com/jedahan/slackin), created a new now.sh deployment, and set the alias to nycmesh.net - It is now hidden:

<img width="282" alt="screen shot 2017-07-16 at 12 47 39 pm" src="https://user-images.githubusercontent.com/32407/28249505-04418fd0-6a25-11e7-9ef1-a8059c8bbb8b.png">
