### ISSUE TITLE
Suggestion: Host firmware releases using native Github functionality

### ISSUE THREAD

**Issue by emersonian** [nycmeshnet/nycmeshnet.github.io#41]
Rather than hosting firmwares exclusively here in the Github-hosted site, it would be a more typical project layout to host them in Github's "Releases" tab in the nycmeshfeed repo so that they are easier to browse and read the release notes of.

Just a quick suggestion as I get up to speed. Great work thus far everyone.

**Comment by emersonian** [comment]
Found it, disregard this. Working on documenting where everything's at.

https://github.com/nycmeshnet/lime-sdk/releases

**Comment by josmo** [comment]
Closing issue since we're already using releases
