### ISSUE TITLE
Add preferred language to join form

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [nycmeshnet/nycmeshnet.github.io#51]
We should try to:
* make people whose preferred language is not English feel welcome when visiting our website
* better communicate during installs
* let volunteers build relationships with users and communities through improved communication
* assess our outreach to under-served users

Preferred language should be a free-form field. We could include a `placeholder`attribute that suggests a few languages e.g. "Spanish, Tagalog, American Sign Language".

**Comment by woa100** [comment]
Agree to all but first point @WIZARDISHUNGRY  - if no-one at mesh speaks Spanish/Tagalog/ASL, etc. may give the wrong impression that we can provide support in that language.  I think the whole languages thing requires a bigger discussion and action plan. Perhaps we can discuss at a content-focused website followup meeting.

**Comment by woa100** [comment]
But I like the idea of collecting that information. In general would be good to work on our install / user analytics collection abilities.

**Comment by WIZARDISHUNGRY** [comment]
hm, maybe best to leave the box blank!

re: installs, we could follow up with an outreach for volunteers (Do *you* speak tagalog?) 2 weeks or so after a successful install is processed.

**Comment by woa100** [comment]
Super agree about follow-ups. Was talking about this a while ago, but lost the plot. Want to see if we can adapt the ticketing system to remind the install leader to follow up as you say a couple weeks, maybe a month later, including a form autoreply if the install leader wants to use it.

On my installs so far, I have made a point of encouraging new members to consider volunteering and to come out to the meetups.

**Comment by woa100** [comment]
Now, also, see... dang it, I knew this would happen... we should really be having this convo on slack. Could you start a thread in install-team channel and copy over some of this conversation?

**Comment by woa100** [comment]
(ie. to open it to more installers and language-speakers who don't do website devel)

**Comment by wizardishungry** [comment]
Closing because this repo is defunct.
