### ISSUE TITLE
Dead space

### ISSUE THREAD

**Issue by codysnider** [nycmeshnet/nycmeshnet.github.io#6]
![capture1](https://cloud.githubusercontent.com/assets/1554995/9982222/8b84d7e8-5fa2-11e5-9869-f84d1beecfb9.PNG)

**Comment by codysnider** [comment]
This is Chrome under Windows 10

Applying #map img { width: 100%; } seems to fix it.

**Comment by bhny** [comment]
Yes this is a new problem as I replaced mapbox with an image that is 1500 px wide. If your browser window is wider than that, yes white space. Width 100% would distort it though wouldn't it? 
(mapbox is very slow to load and actually costs money per tile loaded)

**Comment by codysnider** [comment]
Yow. Why are we using a service that charges for a header image?

**Comment by bhny** [comment]
I'm not a fan of mapbox, but now it is only used on map page so we should stay within budget. I'd like to switch to straight openstreetmap or libremap or even google.

**Comment by bhny** [comment]
It is a minor problem but still happens on Mac in Chrome with browser wider than 1500 pixels.

**Comment by codysnider** [comment]
Who cares what happens on Macs, amiright? (high fives the other old school devs) ..... oh.... right

**Comment by bhny** [comment]
Ha, yea it looks bad, but that is kind of a huge width for a browser.

**Comment by codysnider** [comment]
I use Bootstrap for all my professional shit, ends up real nice for most/all cases. See:
http://ucbtheatre.com
http://ucbtrainingcenter.com

Mac users be damned.... or not. I'm a Windows users, but grids work well for everyone.

**Comment by xtream1101** [comment]
There will be a space on either side of the image on screens wider then 1500px, but at least now it should be centered. It can not stretch beyond that with out looking weird.
