### ISSUE TITLE
Buttons on home screen are too big on Android

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmeshnet.github.io#9]
"Request new node" ..."email" all 8 or so buttons are wider than the screen. made even worse by ability to side-scroll

![2015-12-27 01 09 23](https://cloud.githubusercontent.com/assets/1037006/12008530/8d94787c-ac0f-11e5-8ed9-1154246321d3.png)

**Comment by xtream1101** [comment]
I was not able to reproduce this issue. Please reply with your phone model and browser you are using.

This is a screen shot of it on my Note 4 in chrome, ![](http://i.imgur.com/31ZHneD.png)

**Comment by bhny** [comment]
screenshot is nexus 5, also happens on nexus 4
